(part "IHLP4040DZER4R7M01"
    (packageRef "INDPM108102X400N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "Vishay")
    (property "Manufacturer_Part_Number" "IHLP4040DZER4R7M01")
    (property "Mouser_Part_Number" "70-IHLP4040DZER4R7M0")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Vishay-Dale/IHLP4040DZER4R7M01?qs=gMuw6kkpPFgj12zCspJ5MQ%3D%3D")
    (property "Arrow_Part_Number" "IHLP4040DZER4R7M01")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/ihlp4040dzer4r7m01/vishay?utm_currency=USD&region=nac")
    (property "Description" "Vishay IHLP4040DZ-01 Series Shielded Wire-wound SMD Inductor 4.7 uH +/-20% 9.5A Idc")
    (property "Datasheet_Link" "https://www.vishay.com/docs/34193/ihlp-4040dz-01.pdf")
    (property "symbolName1" "IHLP4040DZER4R7M01")
)
