(part "CSD18513Q5A"
    (packageRef "Q5A_VSON-FET")
    (interface
        (port "1" (symbPinId 1) (portName "S_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S_3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "G") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D_1") (portType INOUT))
        (port "6" (symbPinId 6) (portName "D_2") (portType INOUT))
        (port "7" (symbPinId 7) (portName "D_3") (portType INOUT))
        (port "8" (symbPinId 8) (portName "D_4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "CSD18513Q5A")
    (property "Mouser_Part_Number" "595-CSD18513Q5A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/CSD18513Q5A?qs=34RfhUjJmKfal%252BAkBmQt6Q%3D%3D")
    (property "Arrow_Part_Number" "CSD18513Q5A")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/csd18513q5a/texas-instruments?region=nac")
    (property "Description" "40V, N ch NexFET MOSFET, single SON5x6, 3.4mOhm")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/csd18513q5a")
    (property "symbolName1" "CSD18513Q5A")
)
