(part "SLF12575T-150M4R7-PF"
    (packageRef "SLF12575")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "33")
    (property "Manufacturer_Name" "TDK")
    (property "Manufacturer_Part_Number" "SLF12575T-150M4R7-PF")
    (property "Mouser_Part_Number" "810-SLF12575T-150M")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/TDK/SLF12575T-150M4R7-PF?qs=70au2ePzUrHCA64L9PZ1nA%3D%3D")
    (property "Arrow_Part_Number" "SLF12575T-150M4R7-PF")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/slf12575t-150m4r7-pf/tdk?region=nac")
    (property "Description" "TDK SLF12575 Series Wire-wound SMD Inductor 15 uH +/-20% 5A Idc")
    (property "Datasheet_Link" "https://product.tdk.com/system/files/dam/doc/product/inductor/inductor/smd/catalog/inductor_commercial_power_slf12575_en.pdf")
    (property "symbolName1" "SLF12575T-150M4R7-PF")
)
