(part "KGM15BR71E104KT"
    (packageRef "CAPC1608X95N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Manufacturer_Name" "Kyocera AVX")
    (property "Manufacturer_Part_Number" "KGM15BR71E104KT")
    (property "Mouser_Part_Number" "581-KGM15BR71E104KT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/KYOCERA-AVX/KGM15BR71E104KT?qs=Jm2GQyTW%2FbiCo%2Fby4Q068Q%3D%3D")
    (property "Arrow_Part_Number" "KGM15BR71E104KT")
    (property "Arrow_Price/Stock" "https://www.arrow.com/en/products/kgm15br71e104kt/avx?utm_currency=USD&region=europe")
    (property "Description" "0603 25 V X7R 100nF +/-10%")
    (property "Datasheet_Link" "https://spicat.kyocera-avx.com/product/mlcc/chartview/KGM15BR71E104KT")
    (property "symbolName1" "KGM15BR71E104KT")
)
